// AUTO-GENERATED by bench/export-patterns.mjs — do not edit by hand.
//
// Alternative background patterns for <Glow pattern="…" />. Each is a
// self-contained single-pass fragment shader sharing the component's uniform
// block, so every pattern responds to the same `colors`, `zoom`, `rotation`
// and `speed` props. The default `fold` pattern is not here — it lives in
// foldGradientShader.ts because it is the one shader that needs the baked noise
// LUT and the banded two-pass renderer.

export type PatternName =
	| 'fold'
	| 'aurora'
	| 'curl'
	| 'ink'
	| 'oilfilm'
	| 'marble'
	| 'caustics'
	| 'prism'
	| 'soapfilm'
	| 'dither'
	| 'halftone'
	| 'mesh';

export const PATTERN_NAMES: PatternName[] = [
	'fold',
	'aurora',
	'curl',
	'ink',
	'oilfilm',
	'marble',
	'caustics',
	'prism',
	'soapfilm',
	'dither',
	'halftone',
	'mesh'
];

// One-line descriptions, handy for docs and demo pages.
export const PATTERN_DESCRIPTIONS: Record<PatternName, string> = {
	fold: 'Soft folded sheets of light — the original Glow gradient',
	aurora: "Northern-lights curtains — meandering ribbons with fine vertical rays",
	curl: "Silky curl-noise streamlines; dye smeared along a flowing vector field",
	ink: "Ink in water — thresholded diffusion fronts with feathered tendrils",
	oilfilm: "Iridescent liquid light; thin-film interference over a flowing surface",
	marble: "Polished stone slab with crossing calcite vein families",
	caustics: "Sharp filament network shimmering over a depth-graded pool",
	prism: "Light-slits fanned into spectra by a warped glass wedge",
	soapfilm: "Iridescent film with thin order-contours, marbled by convection",
	dither: "Chunky ordered dither; a drifting light posterised into woven shells",
	halftone: "Screen-printed halftone, three inks on classic separation angles",
	mesh: "Soft gradient mesh — one drifting control point per palette colour"
};

// Per-pattern animation-rate normalisation, so `speed={1}` is the same rate of
// motion on every pattern. Tuned by eye with all twelve side by side; `fold` is
// the reference at 1.0.
export const PATTERN_TIME_SCALE: Record<PatternName, number> = {
	fold: 1,
	aurora: 0.079,
	curl: 0.39,
	ink: 0.19,
	oilfilm: 0.26,
	marble: 0.192,
	caustics: 0.084,
	prism: 0.845,
	soapfilm: 2.005,
	dither: 0.875,
	halftone: 0.995,
	mesh: 0.57
};

// Northern-lights curtains — meandering ribbons with fine vertical rays
// Source: bench/variants/pat-flow-aurora.js
const AURORA = /* glsl */ `#version 300 es
precision highp float;

uniform float u_time;
uniform vec2  u_resolution;
uniform vec4  u_colors[5];
uniform float u_ncols;
uniform vec3  u_back;
uniform vec3  u_shadow;
uniform float u_softness;
uniform float u_saturation;
uniform float u_noise;
uniform float u_rotation;
uniform float u_folds;
uniform float u_ribbon;
uniform float u_ribbonWidth;
// Universal 0..1 morph axis. 0 is the pattern's resting form (bit-identical to
// the pre-morph shader), 1 is a distinctly different but same-family form.
// Every use of it must be a mix/lerp — no floor(), threshold or branch on it,
// or an animated sweep will pop.
uniform float u_morph;

out vec4 fragColor;

mat2 rot(float a){ float c=cos(a), s=sin(a); return mat2(c,-s,s,c); }

vec3 palette(float x){
  x=clamp(x,0.0,1.0)*(u_ncols-1.0);
  int i=int(floor(x)); float f=fract(x);
  return mix(u_colors[i].rgb, u_colors[min(i+1,int(u_ncols)-1)].rgb, smoothstep(0.0,1.0,f));
}
// Seamless ping-pong version, for anything that cycles the ramp.
vec3 paletteLoop(float x){ return palette(abs(fract(x*0.5)*2.0-1.0)); }

vec3 mod289(vec3 x){ return x-floor(x*(1.0/289.0))*289.0; }
vec2 mod289(vec2 x){ return x-floor(x*(1.0/289.0))*289.0; }
vec3 permute(vec3 x){ return mod289(((x*34.0)+1.0)*x); }

// Standard 2D simplex noise, range ~[-1,1]. Pure ALU: no hash texture, and
// cheaper per unit of visual detail than 4x hash12 value noise.
float snoise(vec2 v){
  const vec4 C=vec4(0.211324865405187,0.366025403784439,-0.577350269189626,0.024390243902439);
  vec2 i=floor(v+dot(v,C.yy));
  vec2 x0=v-i+dot(i,C.xx);
  vec2 i1=(x0.x>x0.y)?vec2(1.0,0.0):vec2(0.0,1.0);
  vec4 x12=x0.xyxy+C.xxzz; x12.xy-=i1;
  i=mod289(i);
  vec3 p=permute(permute(i.y+vec3(0.0,i1.y,1.0))+i.x+vec3(0.0,i1.x,1.0));
  vec3 m=max(0.5-vec3(dot(x0,x0),dot(x12.xy,x12.xy),dot(x12.zw,x12.zw)),0.0);
  m=m*m; m=m*m;
  vec3 x=2.0*fract(p*C.www)-1.0;
  vec3 h=abs(x)-0.5; vec3 ox=floor(x+0.5); vec3 a0=x-ox;
  m*=1.79284291400159-0.85373472095314*(a0*a0+h*h);
  vec3 g; g.x=a0.x*x0.x+h.x*x0.y; g.yz=a0.yz*x12.xz+h.yz*x12.yw;
  return 130.0*dot(m,g);
}

const mat2 M2=mat2(0.80,-0.60,0.60,0.80);
float fbm2(vec2 p){ float f=0.60*snoise(p); p=M2*p*2.03; f+=0.30*snoise(p); return f/0.90; }
float fbm3(vec2 p){ float f=0.55*snoise(p); p=M2*p*2.02; f+=0.27*snoise(p); p=M2*p*2.05; f+=0.13*snoise(p); return f/0.95; }

float bayer4(vec2 p){
  int m[16]=int[16](0,8,2,10, 12,4,14,6, 3,11,1,9, 15,7,13,5);
  return float(m[int(mod(p.y,4.0))*4 + int(mod(p.x,4.0))])/16.0;
}

// House-style output chain: ACES-ish tonemap, gamma, saturation, dither.
vec3 finish(vec3 col){
  col=clamp((col*(2.51*col+0.03))/(col*(2.43*col+0.59)+0.14),0.0,1.0);
  col=pow(col, vec3(1.0/2.2));
  float luma=dot(col, vec3(0.2126,0.7152,0.0722));
  col=clamp(mix(vec3(luma), col, u_saturation),0.0,1.0);
  float lvl=mix(255.0,14.0,clamp(u_noise,0.0,1.0));
  col+=(bayer4(gl_FragCoord.xy)-0.5)/lvl;
  return floor(col*lvl+0.5)/lvl;
}

void main(){
  vec2 uv = gl_FragCoord.xy/u_resolution.xy;
  float asp = u_resolution.x/u_resolution.y;
  vec2 p = vec2((uv.x-0.5)*asp, uv.y-0.5);
  // Aurora wants to stay roughly upright, so rotation only leans the curtains.
  p *= rot(radians(u_rotation)*0.22);
  float sc = 9.0/max(u_folds,1.0);
  float t = u_time;
  // morph: hanging curtains (0) -> corona, the rays converging on a point above
  // the frame and the whole sky filling with them (1).
  float mo = clamp(u_morph, 0.0, 1.0);

  // Sky: dark at the top, faint shadow-tinted airglow toward the horizon.
  vec3 col = mix(u_shadow*1.05, u_back, smoothstep(-0.50, 0.60, p.y));

  float glowAcc = 0.0;
  for(int i=0;i<3;i++){
    float fi = float(i);
    float depth = 1.0 - fi*0.28;            // further curtains are dimmer/smaller
    vec2 q = p*sc/ (0.90 + fi*0.38);
    // Perspective fan. Stretching the lateral coordinate proportionally to
    // height turns the lines of constant curtain-coordinate from vertical into
    // a pencil of lines meeting at q.y = 1/(0.48*mo) — off the top of the frame
    // even at mo=1, so it reads as looking up toward the magnetic zenith rather
    // than as a pinched knot. Continuous in mo (mo=0 is a divide by exactly 1)
    // and the clamp keeps the denominator away from zero at any aspect.
    q.x *= 1.0/(1.0 - mo*0.48*clamp(q.y, -1.4, 1.4));
    q.x += fi*3.7 - t*0.030*(1.0+fi*0.6);   // lateral drift, each layer at its own rate

    // Sideways meander of the curtain sheet.
    float xw = q.x + 0.85*snoise(vec2(q.x*0.42, t*0.090 + fi*5.0))
                   + 0.28*snoise(vec2(q.x*1.30 + fi*2.0, t*0.150));

    // Curtain ribbons: thin bright bands on the zero-contours of a 1D field.
    float cur  = fbm2(vec2(xw*0.95 + fi*11.0, t*0.050));
    // u_softness widens the curtain from a hard blade to a broad wash.
    float band = exp(-abs(cur)*mix(8.0,11.5,mo)/clamp(u_softness,0.3,2.5));
    // Gate whole stretches of the sky to nothing. Without this the curtains
    // tile the full width and the frame has no rest. The corona opens the gate
    // up: a full-sky display leaves much less of the sky dark.
    band *= smoothstep(mix(0.10,-0.18,mo), mix(0.62,0.42,mo), 0.5+0.5*snoise(vec2(xw*0.26 - t*0.035, fi*7.0)));

    // Vertical rays, the fine striation that makes an aurora read as an aurora.
    float ray = 0.34 + 0.66*(0.5+0.5*snoise(vec2(xw*5.5, q.y*0.50 - t*0.24 + fi*3.0)));
    ray *= 0.62 + 0.38*(0.5+0.5*snoise(vec2(xw*15.0, q.y*0.26 - t*0.42)));

    // Height profile: crisp lower edge, long exponential fade upward. The
    // corona drops the foot below the frame and stretches the fade, so the rays
    // run the full height instead of hanging off a horizon line.
    float base = mix(-0.48,-0.95,mo) + 0.14*snoise(vec2(xw*0.6 + fi*2.0, t*0.075));
    float hh   = q.y - base;
    float prof = smoothstep(-0.02, mix(0.12,0.42,mo), hh) * exp(-max(hh,0.0)*mix(2.35,0.80,mo));

    // Longer rays over more of the sky is more total light; pull the gain back
    // so the corona is a different shape, not just a brighter frame.
    float inten = band*ray*prof*depth*mix(1.0,0.72,mo);
    // Colour walks up the ramp with altitude: cool at the foot, hot at the tips.
    col += palette(clamp(0.16 + hh*mix(0.80,0.40,mo) + fi*0.05, 0.0, 1.0)) * inten * 1.45;
    // A wide, ray-free halo so the curtains sit in their own light.
    glowAcc += band*prof*depth*0.25;
  }

  col += palette(0.40)*glowAcc*0.45;

  // Faint horizon bloom picking up the palette's low end.
  col += palette(0.06)*exp(-max(p.y+0.46,0.0)*5.0)*0.16;

  // Very slight vignette so text sits on a calmer frame edge.
  vec2 vc=(uv-0.5); vc.x*=asp;
  col *= 1.0 - dot(vc,vc)*0.30;

  fragColor = vec4(finish(col), 1.0);
}
`;

// Silky curl-noise streamlines; dye smeared along a flowing vector field
// Source: bench/variants/pat-flow-curl.js
const CURL = /* glsl */ `#version 300 es
precision highp float;

uniform float u_time;
uniform vec2  u_resolution;
uniform vec4  u_colors[5];
uniform float u_ncols;
uniform vec3  u_back;
uniform vec3  u_shadow;
uniform float u_softness;
uniform float u_saturation;
uniform float u_noise;
uniform float u_rotation;
uniform float u_folds;
uniform float u_ribbon;
uniform float u_ribbonWidth;
// Universal 0..1 morph axis. 0 is the pattern's resting form (bit-identical to
// the pre-morph shader), 1 is a distinctly different but same-family form.
// Every use of it must be a mix/lerp — no floor(), threshold or branch on it,
// or an animated sweep will pop.
uniform float u_morph;

out vec4 fragColor;

mat2 rot(float a){ float c=cos(a), s=sin(a); return mat2(c,-s,s,c); }

vec3 palette(float x){
  x=clamp(x,0.0,1.0)*(u_ncols-1.0);
  int i=int(floor(x)); float f=fract(x);
  return mix(u_colors[i].rgb, u_colors[min(i+1,int(u_ncols)-1)].rgb, smoothstep(0.0,1.0,f));
}
// Seamless ping-pong version, for anything that cycles the ramp.
vec3 paletteLoop(float x){ return palette(abs(fract(x*0.5)*2.0-1.0)); }

vec3 mod289(vec3 x){ return x-floor(x*(1.0/289.0))*289.0; }
vec2 mod289(vec2 x){ return x-floor(x*(1.0/289.0))*289.0; }
vec3 permute(vec3 x){ return mod289(((x*34.0)+1.0)*x); }

// Standard 2D simplex noise, range ~[-1,1]. Pure ALU: no hash texture, and
// cheaper per unit of visual detail than 4x hash12 value noise.
float snoise(vec2 v){
  const vec4 C=vec4(0.211324865405187,0.366025403784439,-0.577350269189626,0.024390243902439);
  vec2 i=floor(v+dot(v,C.yy));
  vec2 x0=v-i+dot(i,C.xx);
  vec2 i1=(x0.x>x0.y)?vec2(1.0,0.0):vec2(0.0,1.0);
  vec4 x12=x0.xyxy+C.xxzz; x12.xy-=i1;
  i=mod289(i);
  vec3 p=permute(permute(i.y+vec3(0.0,i1.y,1.0))+i.x+vec3(0.0,i1.x,1.0));
  vec3 m=max(0.5-vec3(dot(x0,x0),dot(x12.xy,x12.xy),dot(x12.zw,x12.zw)),0.0);
  m=m*m; m=m*m;
  vec3 x=2.0*fract(p*C.www)-1.0;
  vec3 h=abs(x)-0.5; vec3 ox=floor(x+0.5); vec3 a0=x-ox;
  m*=1.79284291400159-0.85373472095314*(a0*a0+h*h);
  vec3 g; g.x=a0.x*x0.x+h.x*x0.y; g.yz=a0.yz*x12.xz+h.yz*x12.yw;
  return 130.0*dot(m,g);
}

const mat2 M2=mat2(0.80,-0.60,0.60,0.80);
float fbm2(vec2 p){ float f=0.60*snoise(p); p=M2*p*2.03; f+=0.30*snoise(p); return f/0.90; }
float fbm3(vec2 p){ float f=0.55*snoise(p); p=M2*p*2.02; f+=0.27*snoise(p); p=M2*p*2.05; f+=0.13*snoise(p); return f/0.95; }

float bayer4(vec2 p){
  int m[16]=int[16](0,8,2,10, 12,4,14,6, 3,11,1,9, 15,7,13,5);
  return float(m[int(mod(p.y,4.0))*4 + int(mod(p.x,4.0))])/16.0;
}

// House-style output chain: ACES-ish tonemap, gamma, saturation, dither.
vec3 finish(vec3 col){
  col=clamp((col*(2.51*col+0.03))/(col*(2.43*col+0.59)+0.14),0.0,1.0);
  col=pow(col, vec3(1.0/2.2));
  float luma=dot(col, vec3(0.2126,0.7152,0.0722));
  col=clamp(mix(vec3(luma), col, u_saturation),0.0,1.0);
  float lvl=mix(255.0,14.0,clamp(u_noise,0.0,1.0));
  col+=(bayer4(gl_FragCoord.xy)-0.5)/lvl;
  return floor(col*lvl+0.5)/lvl;
}

// Direction field. A single angle from noise rather than a true curl, which
// looks the same at this scale for a third of the cost.
// morph damps the angle field toward a single direction while stretching its
// wavelength: turbulence relaxing into laminar flow. Interpolating the *angle*
// (a plain continuous float field, never a wrapped one) rather than blending
// two direction vectors is what keeps this pop-free — blended vectors go
// degenerate wherever the two fields point opposite ways.
vec2 flowDir(vec2 p, float t, float mo){
  // Both knobs are applied as multiplies by exactly 1.0 at mo=0 — the frequency
  // onto p before the untouched literal, the damping onto the finished angle —
  // so the mo=0 arithmetic is the original expression unchanged.
  vec2 pf = p*mix(1.0,0.52,mo);
  float a = 3.14159*( snoise(pf*0.55 + vec2(0.0, t*0.045))
                    + 0.45*snoise(pf*1.45 - vec2(t*0.030, 0.0)) );
  a *= mix(1.0,0.38,mo);
  return vec2(cos(a), sin(a));
}

// Dye frequency has to stay low relative to the tap spacing of the walk below.
// At 7.5 the 13 taps aliased against the dye and produced a crosshatch moire
// instead of a smear; the whole look depends on oversampling the dye.
// A laminar walk is combed further per tap (see the walk step in main), so the
// dye has to coarsen with it or the taps undersample it and the silk turns into
// a blotchy moire — which is exactly what a longer step alone produced. Keeping
// (1/freq)/step at ~3.3 across the whole morph range is the constraint.
float dye(vec2 p, float t, float mo){
  return 0.5+0.5*snoise(p*mix(1.0,0.80,mo)*3.0 + vec2(t*0.22, -t*0.13));
}

void main(){
  vec2 uv = gl_FragCoord.xy/u_resolution.xy;
  float asp = u_resolution.x/u_resolution.y;
  vec2 p = vec2((uv.x-0.5)*asp, uv.y-0.5);
  p *= rot(radians(u_rotation));
  float sc = 9.0/max(u_folds,1.0);
  float t = u_time;
  // morph: turbulent curl (0) -> combed laminar satin, long parallel streaks
  // running along the u_rotation axis (1).
  float mo = clamp(u_morph, 0.0, 1.0);

  vec2 q = p*sc*1.15;

  const int N = 14;
  // u_softness sets how far the dye is smeared, i.e. how silky the streaks get.
  // Laminar flow can be combed much further before the walk curls back on
  // itself, and the long smear is most of what sells the change of state.
  float step = 0.100*clamp(u_softness,0.4,2.0)*mix(1.0,1.30,mo);
  vec2 f = q, b = q;
  float acc = 0.0, wsum = 0.0;
  vec2 dSum = vec2(0.0);
  for(int i=0;i<N;i++){
    float w = 1.0 - float(i)/float(N);
    vec2 df = flowDir(f,t,mo); vec2 db = flowDir(b,t,mo);
    dSum += df;
    f += df*step;
    b -= db*step;
    acc += (dye(f,t,mo)+dye(b,t,mo))*w;
    wsum += 2.0*w;
  }
  acc /= wsum;

  // The average along a streamline is low-variance; stretch it back out.
  // A straight walk averages more dye periods than a curled one, so the laminar
  // end comes back flatter; give it a little more stretch to compensate.
  float streak = clamp((acc-0.5)*3.0*mix(1.0,1.17,mo)+0.5, 0.0, 1.0);

  // Coherence: where the walk stayed straight the streak is a long clean line,
  // where it curled tightly it is a knot. That difference is the composition.
  float coh = length(dSum)/float(N);

  // Local flow orientation nudges hue, so the palette tracks direction. Kept to
  // a narrow slice of the ramp: a full sweep turns the frame into hard red/blue
  // patchwork rather than one flowing material.
  // NB: atan(y,x) is *not* usable here — its branch cut at +/-pi draws a hard
  // seam straight across the image. Project the direction onto a fixed axis
  // instead, which is continuous everywhere.
  vec2 d0 = flowDir(q,t,mo);
  float hue = clamp(0.5+0.5*dot(d0, vec2(0.60,0.80)), 0.0, 1.0);

  // Large-scale envelope: most of the frame is quiet water, and the streaks
  // only come up to full brightness in a few drifting regions. Laminar flow
  // covers the frame, so the envelope opens as morph rises.
  float envRaw = 0.5+0.5*snoise(q*0.34 + vec2(t*0.055, -t*0.030));
  float env = smoothstep(mix(0.20,0.06,mo), mix(0.92,0.80,mo), envRaw);

  // Once the flow is laminar every pixel points the same way, so a direction-
  // driven hue collapses to one flat colour. Replace it with a field sampled
  // 8x tighter across the flow than along it, which lays colour down as
  // striations parallel to the combing instead of as blobs.
  vec2 pd = vec2(-d0.y, d0.x);
  float hueLam = clamp(0.5+0.62*snoise(vec2(dot(q,pd)*0.85, dot(q,d0)*0.10)), 0.0, 1.0);
  hue = mix(hue, hueLam, mo*0.85);

  // Coherence is ~1 everywhere in laminar flow; trim the gain so the change
  // reads as shape rather than as exposure.
  float lum = streak*(0.30+0.70*coh)*(0.18+0.95*env)*mix(1.0,0.80,mo);
  vec3 tint = palette(clamp(0.16 + hue*0.34 + streak*0.48, 0.0, 1.0));

  vec3 col = mix(u_back, u_shadow, smoothstep(0.0,0.25,lum));
  col = mix(col, tint*0.85, smoothstep(0.05, 0.62, lum));
  // Filament highlights only where the flow is both bright and coherent.
  col += tint*pow(smoothstep(0.62,1.0,streak),2.0)*coh*env*0.75;

  vec2 vc=(uv-0.5); vc.x*=asp;
  col *= 1.0 - dot(vc,vc)*0.35;

  fragColor = vec4(finish(col), 1.0);
}
`;

// Ink in water — thresholded diffusion fronts with feathered tendrils
// Source: bench/variants/pat-flow-ink.js
const INK = /* glsl */ `#version 300 es
precision highp float;

uniform float u_time;
uniform vec2  u_resolution;
uniform vec4  u_colors[5];
uniform float u_ncols;
uniform vec3  u_back;
uniform vec3  u_shadow;
uniform float u_softness;
uniform float u_saturation;
uniform float u_noise;
uniform float u_rotation;
uniform float u_folds;
uniform float u_ribbon;
uniform float u_ribbonWidth;
// Universal 0..1 morph axis. 0 is the pattern's resting form (bit-identical to
// the pre-morph shader), 1 is a distinctly different but same-family form.
// Every use of it must be a mix/lerp — no floor(), threshold or branch on it,
// or an animated sweep will pop.
uniform float u_morph;

out vec4 fragColor;

mat2 rot(float a){ float c=cos(a), s=sin(a); return mat2(c,-s,s,c); }

vec3 palette(float x){
  x=clamp(x,0.0,1.0)*(u_ncols-1.0);
  int i=int(floor(x)); float f=fract(x);
  return mix(u_colors[i].rgb, u_colors[min(i+1,int(u_ncols)-1)].rgb, smoothstep(0.0,1.0,f));
}
// Seamless ping-pong version, for anything that cycles the ramp.
vec3 paletteLoop(float x){ return palette(abs(fract(x*0.5)*2.0-1.0)); }

vec3 mod289(vec3 x){ return x-floor(x*(1.0/289.0))*289.0; }
vec2 mod289(vec2 x){ return x-floor(x*(1.0/289.0))*289.0; }
vec3 permute(vec3 x){ return mod289(((x*34.0)+1.0)*x); }

// Standard 2D simplex noise, range ~[-1,1]. Pure ALU: no hash texture, and
// cheaper per unit of visual detail than 4x hash12 value noise.
float snoise(vec2 v){
  const vec4 C=vec4(0.211324865405187,0.366025403784439,-0.577350269189626,0.024390243902439);
  vec2 i=floor(v+dot(v,C.yy));
  vec2 x0=v-i+dot(i,C.xx);
  vec2 i1=(x0.x>x0.y)?vec2(1.0,0.0):vec2(0.0,1.0);
  vec4 x12=x0.xyxy+C.xxzz; x12.xy-=i1;
  i=mod289(i);
  vec3 p=permute(permute(i.y+vec3(0.0,i1.y,1.0))+i.x+vec3(0.0,i1.x,1.0));
  vec3 m=max(0.5-vec3(dot(x0,x0),dot(x12.xy,x12.xy),dot(x12.zw,x12.zw)),0.0);
  m=m*m; m=m*m;
  vec3 x=2.0*fract(p*C.www)-1.0;
  vec3 h=abs(x)-0.5; vec3 ox=floor(x+0.5); vec3 a0=x-ox;
  m*=1.79284291400159-0.85373472095314*(a0*a0+h*h);
  vec3 g; g.x=a0.x*x0.x+h.x*x0.y; g.yz=a0.yz*x12.xz+h.yz*x12.yw;
  return 130.0*dot(m,g);
}

const mat2 M2=mat2(0.80,-0.60,0.60,0.80);
float fbm2(vec2 p){ float f=0.60*snoise(p); p=M2*p*2.03; f+=0.30*snoise(p); return f/0.90; }
float fbm3(vec2 p){ float f=0.55*snoise(p); p=M2*p*2.02; f+=0.27*snoise(p); p=M2*p*2.05; f+=0.13*snoise(p); return f/0.95; }

float bayer4(vec2 p){
  int m[16]=int[16](0,8,2,10, 12,4,14,6, 3,11,1,9, 15,7,13,5);
  return float(m[int(mod(p.y,4.0))*4 + int(mod(p.x,4.0))])/16.0;
}

// House-style output chain: ACES-ish tonemap, gamma, saturation, dither.
vec3 finish(vec3 col){
  col=clamp((col*(2.51*col+0.03))/(col*(2.43*col+0.59)+0.14),0.0,1.0);
  col=pow(col, vec3(1.0/2.2));
  float luma=dot(col, vec3(0.2126,0.7152,0.0722));
  col=clamp(mix(vec3(luma), col, u_saturation),0.0,1.0);
  float lvl=mix(255.0,14.0,clamp(u_noise,0.0,1.0));
  col+=(bayer4(gl_FragCoord.xy)-0.5)/lvl;
  return floor(col*lvl+0.5)/lvl;
}

void main(){
  vec2 uv = gl_FragCoord.xy/u_resolution.xy;
  float asp = u_resolution.x/u_resolution.y;
  vec2 p = vec2((uv.x-0.5)*asp, uv.y-0.5);
  p *= rot(radians(u_rotation));
  float sc = 9.0/max(u_folds,1.0);
  float t = u_time;
  // morph: one diffusion front (0) -> the same dye stratified into nested
  // concentration shells, ink read as agate banding (1).
  float mo = clamp(u_morph, 0.0, 1.0);

  vec2 q = p*sc*1.05;

  // Gentle vortex: rotation rate falls off with radius, so the middle of the
  // frame shears against its surroundings instead of spinning rigidly.
  // Winds and unwinds rather than accumulating: a monotonic t here would keep
  // twisting the middle of the frame forever and eventually alias into mush.
  float r = length(q);
  q *= rot(1.35*sin(t*0.055)/(0.55+r*r*0.55));

  // Turbulent warp, coarse to fine. Each level rides on the previous one.
  vec2 w = q;
  w += 0.50*vec2(snoise(q*0.80 + vec2(t*0.045,0.0)),
                 snoise(q*0.80 + vec2(5.2,1.3) - vec2(0.0,t*0.038)));
  w += 0.24*vec2(snoise(w*2.0 + vec2(0.0,t*0.085)),
                 snoise(w*2.0 + vec2(3.7,8.1)));
  // Morph gain multiplies the inner vector, not the 0.10 literal, so at mo=0 it
  // is a multiply by exactly 1.0 and the outer expression is unchanged.
  w += 0.10*(vec2(snoise(w*4.4 - vec2(t*0.12,0.0)),
                  snoise(w*4.4 + vec2(1.1,6.6)))*mix(1.0,1.70,mo));

  // Concentration. The threshold makes a diffusion front rather than a haze,
  // and sits high enough that most of the tank is still clear water.
  float raw = 0.5+0.5*snoise(w*0.55);
  // A wide front, not a hard edge: ink bleeds, it does not get cut out.
  // u_softness controls how far the dye has bled: the width of the front.
  float c   = smoothstep(0.46 - 0.12*(clamp(u_softness,0.3,2.5)-1.0), 0.95, raw);
  // Morph reshapes the transfer function applied to raw rather than blending
  // in a second field, so every contour of the dye stays exactly where it was
  // and the single front simply splits into a stack of shells. cos() keeps it
  // periodic without a fract()/floor() edge to pop on.
  float shells = smoothstep(0.30, 0.92, 0.5-0.5*cos(6.2831*(raw*3.1+0.12)))
               * smoothstep(0.16, 0.52, raw);
  // Written as an additive delta rather than mix(c,shells,mo): at mo=0 this is
  // an add of exactly 0.0 in a statement of its own, which leaves the code that
  // produced c untouched and keeps mo=0 bit-identical to the pre-morph shader.
  c += mo*(shells - c);
  // Finer secondary dye, only visible inside the main mass.
  float c2  = 0.5+0.5*snoise(w*1.45 + vec2(2.4,7.1));
  // Fine wisps. Without this the concentration contours come out as smooth
  // concentric bands and the whole thing reads as poured enamel, not dye.
  float wisp = 0.5+0.5*snoise(w*3.4 + vec2(0.0, t*0.06));
  float dens = clamp(c*(0.55+0.60*c2)*(0.70+0.55*wisp), 0.0, 1.0);

  // Filament edges: the gradient of the concentration lights up the fronts.
  float rim = length(vec2(dFdx(dens), dFdy(dens)))*u_resolution.y*0.035;
  rim = clamp(rim,0.0,1.0);

  // Depth: a faint, much larger and slower second cloud behind everything.
  float back = smoothstep(0.45,1.0, 0.5+0.5*snoise(w*0.24 - vec2(t*0.02,0.0)));

  // The diffuse halo: dye that has already spread out past the visible mass.
  float halo = smoothstep(0.26, 0.80, raw);

  vec3 col = mix(u_back, u_shadow, back*0.9);
  col += palette(0.08)*back*0.12;
  col += palette(clamp(0.16+halo*0.18,0.0,1.0))*halo*halo*0.075;
  col = mix(col, palette(clamp(0.20 + dens*0.44 + c2*0.12, 0.0, 1.0))*0.52, smoothstep(0.02,0.90,dens));
  // Fronts get a soft lift, not a specular rim; the glossy version read as
  // enamel rather than as dye.
  col += palette(clamp(0.45+dens*0.30,0.0,1.0))*rim*dens*0.22;
  col += palette(0.90)*pow(clamp(dens-0.72,0.0,1.0),1.3)*0.75;  // hot cores

  vec2 vc=(uv-0.5); vc.x*=asp;
  col *= 1.0 - dot(vc,vc)*0.28;

  fragColor = vec4(finish(col), 1.0);
}
`;

// Iridescent liquid light; thin-film interference over a flowing surface
// Source: bench/variants/pat-flow-oilfilm.js
const OILFILM = /* glsl */ `#version 300 es
precision highp float;

uniform float u_time;
uniform vec2  u_resolution;
uniform vec4  u_colors[5];
uniform float u_ncols;
uniform vec3  u_back;
uniform vec3  u_shadow;
uniform float u_softness;
uniform float u_saturation;
uniform float u_noise;
uniform float u_rotation;
uniform float u_folds;
uniform float u_ribbon;
uniform float u_ribbonWidth;
// Universal 0..1 morph axis. 0 is the pattern's resting form (bit-identical to
// the pre-morph shader), 1 is a distinctly different but same-family form.
// Every use of it must be a mix/lerp — no floor(), threshold or branch on it,
// or an animated sweep will pop.
uniform float u_morph;

out vec4 fragColor;

mat2 rot(float a){ float c=cos(a), s=sin(a); return mat2(c,-s,s,c); }

vec3 palette(float x){
  x=clamp(x,0.0,1.0)*(u_ncols-1.0);
  int i=int(floor(x)); float f=fract(x);
  return mix(u_colors[i].rgb, u_colors[min(i+1,int(u_ncols)-1)].rgb, smoothstep(0.0,1.0,f));
}
// Seamless ping-pong version, for anything that cycles the ramp.
vec3 paletteLoop(float x){ return palette(abs(fract(x*0.5)*2.0-1.0)); }

vec3 mod289(vec3 x){ return x-floor(x*(1.0/289.0))*289.0; }
vec2 mod289(vec2 x){ return x-floor(x*(1.0/289.0))*289.0; }
vec3 permute(vec3 x){ return mod289(((x*34.0)+1.0)*x); }

// Standard 2D simplex noise, range ~[-1,1]. Pure ALU: no hash texture, and
// cheaper per unit of visual detail than 4x hash12 value noise.
float snoise(vec2 v){
  const vec4 C=vec4(0.211324865405187,0.366025403784439,-0.577350269189626,0.024390243902439);
  vec2 i=floor(v+dot(v,C.yy));
  vec2 x0=v-i+dot(i,C.xx);
  vec2 i1=(x0.x>x0.y)?vec2(1.0,0.0):vec2(0.0,1.0);
  vec4 x12=x0.xyxy+C.xxzz; x12.xy-=i1;
  i=mod289(i);
  vec3 p=permute(permute(i.y+vec3(0.0,i1.y,1.0))+i.x+vec3(0.0,i1.x,1.0));
  vec3 m=max(0.5-vec3(dot(x0,x0),dot(x12.xy,x12.xy),dot(x12.zw,x12.zw)),0.0);
  m=m*m; m=m*m;
  vec3 x=2.0*fract(p*C.www)-1.0;
  vec3 h=abs(x)-0.5; vec3 ox=floor(x+0.5); vec3 a0=x-ox;
  m*=1.79284291400159-0.85373472095314*(a0*a0+h*h);
  vec3 g; g.x=a0.x*x0.x+h.x*x0.y; g.yz=a0.yz*x12.xz+h.yz*x12.yw;
  return 130.0*dot(m,g);
}

const mat2 M2=mat2(0.80,-0.60,0.60,0.80);
float fbm2(vec2 p){ float f=0.60*snoise(p); p=M2*p*2.03; f+=0.30*snoise(p); return f/0.90; }
float fbm3(vec2 p){ float f=0.55*snoise(p); p=M2*p*2.02; f+=0.27*snoise(p); p=M2*p*2.05; f+=0.13*snoise(p); return f/0.95; }

float bayer4(vec2 p){
  int m[16]=int[16](0,8,2,10, 12,4,14,6, 3,11,1,9, 15,7,13,5);
  return float(m[int(mod(p.y,4.0))*4 + int(mod(p.x,4.0))])/16.0;
}

// House-style output chain: ACES-ish tonemap, gamma, saturation, dither.
vec3 finish(vec3 col){
  col=clamp((col*(2.51*col+0.03))/(col*(2.43*col+0.59)+0.14),0.0,1.0);
  col=pow(col, vec3(1.0/2.2));
  float luma=dot(col, vec3(0.2126,0.7152,0.0722));
  col=clamp(mix(vec3(luma), col, u_saturation),0.0,1.0);
  float lvl=mix(255.0,14.0,clamp(u_noise,0.0,1.0));
  col+=(bayer4(gl_FragCoord.xy)-0.5)/lvl;
  return floor(col*lvl+0.5)/lvl;
}

float height(vec2 p, float t){
  // Advected, self-warping surface. The warp offsets move at different rates
  // so the film keeps re-mixing instead of translating.
  vec2 w = p;
  w += 0.55*vec2(snoise(p*0.70 + vec2(t*0.055, 0.0)),
                 snoise(p*0.70 + vec2(2.7,8.3) + vec2(0.0, t*0.041)));
  w += 0.26*vec2(snoise(w*1.65 - vec2(0.0, t*0.09)),
                 snoise(w*1.65 + vec2(5.1,1.9)));
  return fbm3(w*0.85 + vec2(0.0, t*0.02));
}

void main(){
  vec2 uv = gl_FragCoord.xy/u_resolution.xy;
  float asp = u_resolution.x/u_resolution.y;
  vec2 p = vec2((uv.x-0.5)*asp, uv.y-0.5);
  p *= rot(radians(u_rotation));
  float sc = 9.0/max(u_folds,1.0);
  float t = u_time;
  // morph: a still, flowing film (0) -> the same film driven into a standing
  // wave, corrugated into iridescent rings that the surface topography warps (1).
  float mo = clamp(u_morph, 0.0, 1.0);

  vec2 q = p*sc*0.95;

  float h = height(q, t);
  // Phase carries the film's own height, so the rings are pulled about by the
  // topography instead of sitting on the frame as perfect circles.
  vec2  rc = vec2(0.34*sin(t*0.031), -0.20);
  float ripple = sin(6.2831*(length(q-rc)*3.4 + h*0.30) - t*0.30);
  // Corrugating the height itself (not just the colour) is what puts real
  // specular glints along the rings.
  h += mo*0.058*ripple;
  // Derivatives of the height give the surface normal for free.
  vec2 g = vec2(dFdx(h), dFdy(h))*u_resolution.xy*0.010;
  vec3 N = normalize(vec3(-g, 0.55));

  vec3 L = normalize(vec3(0.45, 0.55, 0.70));
  vec3 V = vec3(0.0,0.0,1.0);
  vec3 H = normalize(L+V);
  float diff = clamp(dot(N,L),0.0,1.0);
  // u_softness broadens the highlight: polished film -> satin.
  float spec = pow(clamp(dot(N,H),0.0,1.0), 42.0/clamp(u_softness,0.35,3.0));
  float fres = pow(1.0-clamp(N.z,0.0,1.0), 2.2);

  // Interference: optical path length depends on thickness and view angle, so
  // the bands crowd where the surface tilts away. That crowding is the whole
  // reason this reads as oil on water and not as a colour ramp.
  float thick = h*1.75 + fres*1.30 + 0.28*snoise(q*0.4 + vec2(t*0.03,0.0))
              + mo*0.55*ripple;   // rings crowd the ramp into visible fringes
  vec3 film = paletteLoop(thick);

  // The film is not everywhere. Where it thins out the liquid goes back to
  // near-black, which is what gives the frame somewhere to breathe.
  // The standing wave drives the film out over more of the dish.
  float cover = smoothstep(mix(0.18,0.09,mo), mix(0.86,0.78,mo), 0.5+0.5*snoise(q*0.42 + vec2(-t*0.045, t*0.028)));

  float lum = 0.14 + 0.86*diff;
  vec3 col = mix(u_shadow, u_back, clamp(h*1.4+0.35,0.0,1.0));
  col += film*lum*(0.10 + 0.50*fres)*(0.06+0.95*cover);
  col += film*spec*0.95*(0.20+0.90*cover);
  col += vec3(1.0)*spec*0.18;

  // Dark troughs keep contrast: the film thins to nothing in the low places.
  col *= 0.16 + 1.05*smoothstep(-0.65, 0.55, h);

  vec2 vc=(uv-0.5); vc.x*=asp;
  col *= 1.0 - dot(vc,vc)*0.28;

  fragColor = vec4(finish(col), 1.0);
}
`;

// Polished stone slab with crossing calcite vein families
// Source: bench/variants/pat-org-marble.js
const MARBLE = /* glsl */ `#version 300 es
precision highp float;

uniform float u_time;
uniform vec2  u_resolution;
uniform vec4  u_colors[5];
uniform float u_ncols;
uniform vec3  u_back;
uniform vec3  u_shadow;
uniform float u_softness;
uniform float u_saturation;
uniform float u_noise;
uniform float u_rotation;
uniform float u_folds;
uniform float u_ribbon;
uniform float u_ribbonWidth;
// Universal 0..1 morph axis. 0 is the resting form: thin calcite veins on a
// dark slab. 1 is the same stone cut the other way — the vein families open out
// and the turbulence that scattered them is eased off, so what is left is broad
// banded agate layering.
uniform float u_morph;

out vec4 fragColor;

mat2 rot(float a){ float c=cos(a), s=sin(a); return mat2(c,-s,s,c); }
float h21(vec2 p){ p=fract(p*vec2(123.34,456.21)); p+=dot(p,p+45.32); return fract(p.x*p.y); }
vec2 grad2(vec2 p){ float a=h21(p)*6.2831853; return vec2(cos(a),sin(a)); }
float gn(vec2 p){
  vec2 i=floor(p), f=fract(p);
  vec2 u=f*f*(3.0-2.0*f);
  float a=dot(grad2(i),f);
  float b=dot(grad2(i+vec2(1,0)),f-vec2(1,0));
  float c=dot(grad2(i+vec2(0,1)),f-vec2(0,1));
  float d=dot(grad2(i+vec2(1,1)),f-vec2(1,1));
  return mix(mix(a,b,u.x),mix(c,d,u.x),u.y);
}
const mat2 m2=mat2(0.80,-0.60,0.60,0.80);
float fbm(vec2 p){
  float f=0.5*gn(p); p=m2*p*2.03;
  f+=0.25*gn(p); p=m2*p*2.01;
  f+=0.125*gn(p); p=m2*p*2.02;
  f+=0.0625*gn(p);
  return f;
}
// low-passed version. The vein phase must come from a smooth field: feeding it
// the full fbm makes every vein wobble at pixel scale and the slab reads as
// water rather than stone.
float fbmL(vec2 p){
  float f=0.58*gn(p); p=m2*p*2.03;
  f+=0.29*gn(p);
  return f;
}

vec3 palette(float x){
  x=clamp(x,0.0,1.0)*(u_ncols-1.0);
  int i=int(floor(x)); float f=fract(x);
  return mix(u_colors[i].rgb, u_colors[min(i+1,int(u_ncols)-1)].rgb, f*f*(3.0-2.0*f));
}
float bayer4(vec2 p){
  int m[16]=int[16](0,8,2,10, 12,4,14,6, 3,11,1,9, 15,7,13,5);
  return float(m[int(mod(p.y,4.0))*4 + int(mod(p.x,4.0))])/16.0;
}
vec3 finish(vec3 col){
  col=clamp((col*(2.51*col+0.03))/(col*(2.43*col+0.59)+0.14),0.0,1.0);
  col=pow(col, vec3(1.0/2.2));
  float l=dot(col, vec3(0.2126,0.7152,0.0722));
  col=clamp(mix(vec3(l),col,u_saturation),0.0,1.0);
  float lvl=mix(255.0,14.0,clamp(u_noise,0.0,1.0));
  col+=(bayer4(gl_FragCoord.xy)-0.5)/lvl;
  return floor(col*lvl+0.5)/lvl;
}

void main(){
  vec2 uv=gl_FragCoord.xy/u_resolution.xy;
  float asp=u_resolution.x/u_resolution.y;
  // u_rotation orients the slab; u_folds is the zoom. Written as 0.15*(81/folds)
  // so that at the component default (9) it is bit-for-bit the old 0.15*folds,
  // while the direction now matches every other pattern: larger = larger.
  vec2 p=rot(radians(u_rotation))*vec2((uv.x-0.5)*asp, uv.y-0.5)*(0.15*(81.0/max(u_folds,1.0)));

  float m=clamp(u_morph,0.0,1.0);
  float t=u_time*0.05;

  // domain warp: the slow drift makes the stone look like it is still setting
  vec2 q1=vec2(fbmL(p+vec2(0.0,t)), fbmL(p+vec2(5.2,1.3)-t*0.8));
  vec2 r1=vec2(fbmL(p+2.1*q1+vec2(1.7,9.2)+t*0.6), fbmL(p+2.1*q1+vec2(8.3,2.8)-t*0.4));
  float turb=fbm(p+1.7*r1);
  float turbL=fbmL(p+1.7*r1);

  // primary vein family — sinusoid folded by the turbulence. The morph does two
  // things at once, both continuous: it drains the turbulence out of the phase
  // (so the fold straightens into stratified layers) and drops the exponents
  // that pinch each fold into a hairline (so the layers open into bands).
  // Exponent interpolation is what keeps the sweep pop-free — there is no
  // threshold anywhere, a vein just fattens.
  float s1=sin((p.x*1.15+p.y*0.45+mix(5.4,1.50,m)*turbL+mix(2.2,0.55,m)*r1.x)*mix(1.15,3.20,m));
  float v1=1.0-abs(s1);
  float core=pow(v1,mix(13.0,3.20,m));
  float halo=pow(v1,mix(3.5,1.50,m));

  // secondary, finer, crossing family
  float s2=sin((p.x*0.55-p.y*1.75+mix(4.2,1.40,m)*fbmL(p*1.05+r1*1.8))*mix(1.9,3.10,m));
  float v2=1.0-abs(s2);
  float core2=pow(v2,mix(26.0,6.0,m));

  float veins=core+mix(0.75,0.50,m)*core2;

  // relief for the polish. Only the broad shape gets a normal — taking the
  // derivative of the full turbulence covers the slab in wet-looking ripples.
  float relief=0.55*r1.x+0.35*q1.y+0.30*halo+0.45*core;
  vec2 g=vec2(dFdx(relief),dFdy(relief))*u_resolution.xy*0.0022;
  vec3 N=normalize(vec3(-g,1.0));
  vec3 L=normalize(vec3(0.42,0.62,0.66));
  float diff=0.62+0.45*clamp(dot(N,L),0.0,1.0);
  float spec=pow(clamp(dot(N,normalize(L+vec3(0.0,0.0,1.0))),0.0,1.0),46.0);

  // stone: dark, faintly coloured mottling from the low palette
  // Eased with m*m, not m. The colour shift is by far the loudest part of this
  // morph, and on a linear ramp the slab had finished changing colour by the
  // halfway point while the veins were still only half-open. Squaring is still
  // smooth and still monotonic; it just moves the colour to the back half so
  // the two halves of the change land together.
  float mc=m*m;
  float mott=clamp(turb*1.9+0.5+mix(0.0,0.42,mc)*s1,0.0,1.0);
  vec3 stone=mix(u_back, u_shadow, 0.55);
  // At rest the base tone comes from the darkest palette stop only, so the slab
  // stays stone-coloured and the veins are the only saturated thing in frame.
  // The morph walks that lookup along the ramp in step with the vein phase,
  // which is what turns a veined slab into banded agate: the stone itself picks
  // up the layering instead of the veins being an overlay on a flat field.
  stone=mix(stone, palette(mix(0.0,0.27*(0.5+0.5*s1),mc))*(0.55+0.75*mott), 0.55);
  stone*=diff;

  // veins: bright, colour picked by which turbulence pocket they run through
  // calcite is never a pure hue — pulling the vein colour toward white is what
  // stops it reading as a neon line painted on the slab
  // banded agate takes its colour from which layer you are in, so the morph
  // feeds the fold phase itself into the ramp lookup and lets the bands hold
  // more chroma than a calcite vein would.
  vec3 vcol=mix(palette(clamp(0.42+0.55*r1.y+0.25*q1.x+mix(0.0,0.34,m)*s1,0.0,1.0)), vec3(0.55), mix(0.45,0.34,m));
  vec3 col=stone;
  col=mix(col, vcol*0.18, halo*halo*mix(0.70,0.55,m));
  // a band covers far more of the slab than a hairline vein did, so the gain
  // comes down to keep the dark stone between the layers
  col+=vcol*veins*mix(0.55,0.30,m);
  col+=vec3(1.0)*core*core*mix(0.12,0.06,m);
  col+=vec3(spec)*(0.05+0.16*veins);

  vec2 vc=(uv-0.5); vc.x*=asp;
  col*=1.0-dot(vc,vc)*0.28;

  fragColor=vec4(finish(col),1.0);
}
`;

// Sharp filament network shimmering over a depth-graded pool
// Source: bench/variants/pat-opt-caustics.js
const CAUSTICS = /* glsl */ `#version 300 es
precision highp float;

uniform float u_time;
uniform vec2  u_resolution;
uniform vec4  u_colors[5];
uniform float u_ncols;
uniform vec3  u_back;
uniform vec3  u_shadow;
uniform float u_softness;
uniform float u_saturation;
uniform float u_noise;
uniform float u_rotation;
uniform float u_folds;
uniform float u_ribbon;
uniform float u_ribbonWidth;
// Universal 0..1 morph axis. 0 is the resting form (unchanged from before this
// existed); 1 is the same water, seen differently: the fine dappled net drawn
// out into broad vertical light shafts with heavy chromatic fringing.
uniform float u_morph;

out vec4 fragColor;

const float TAU = 6.28318530718;

mat2 rot(float a){ float c=cos(a), s=sin(a); return mat2(c,-s,s,c); }

vec3 palette(float x){
  x=clamp(x,0.0,1.0)*(u_ncols-1.0);
  int i=int(floor(x)); float f=fract(x);
  return mix(u_colors[i].rgb, u_colors[min(i+1,int(u_ncols)-1)].rgb, smoothstep(0.0,1.0,f));
}

float bayer4(vec2 p){
  int m[16]=int[16](0,8,2,10, 12,4,14,6, 3,11,1,9, 15,7,13,5);
  return float(m[int(mod(p.y,4.0))*4 + int(mod(p.x,4.0))])/16.0;
}

// The classic iterated-refraction caustic: five passes of a self-referential
// warp, each contributing an inverse-distance spike. The reciprocal is what
// makes the filaments thin and hot rather than blobby like fbm. A high final
// exponent is what keeps the network sparse instead of milky.
float caustic(vec2 uv, float t, float inten, float sharp){
  vec2 p = mod(uv*TAU, TAU) - 250.0;
  vec2 i = p;
  float c = 1.0;
  for(int n=0; n<5; n++){
    float tt = t * (1.0 - 3.5/(float(n)+1.0));
    i = p + vec2(cos(tt - i.x) + sin(tt + i.y), sin(tt - i.y) + cos(tt + i.x));
    c += 1.0/length(vec2(p.x/(sin(i.x+tt)/inten), p.y/(cos(i.y+tt)/inten)));
  }
  c /= 5.0;
  c = 1.17 - pow(c, 1.4);
  return pow(abs(c), sharp);
}

void main(){
  vec2 uv = gl_FragCoord.xy/u_resolution.xy;
  float asp = u_resolution.x/u_resolution.y;
  vec2 q = vec2((uv.x-0.5)*asp, uv.y-0.5);

  float m = clamp(u_morph, 0.0, 1.0);

  // u_folds is the zoom: bigger value -> bigger cells (same direction as the
  // fold shader's 29.16/u_folds), and u_rotation orients the net. Deliberately
  // low overall: at higher frequencies the network stops reading as separate
  // filaments and turns into a uniform milky texture.
  float zoom = 0.45 + 5.4/max(u_folds,1.0);
  vec2 p = q*rot(radians(u_rotation))*zoom;

  // Morph coefficients. They are declared with the values the shader has always
  // used and only rewritten when m>0, so morph=0 leaves the arithmetic below
  // byte-for-byte the expression that shipped — no reassociated multiply, no
  // 1-ulp drift through the reciprocal in caustic(), which is sharp enough to
  // turn one into a visible pixel. Every rewrite is a mix() anchored on that
  // same original value, so the branch's effect starts at exactly zero and
  // grows continuously; nothing here can pop.
  float swellAmp = 0.045;
  float sharp    = 15.0 + 3.0/max(u_softness, 0.25);
  // Dispersion: three slightly different refractive scales, so the hot cores
  // fringe apart into colour the way real caustic edges do.
  float disp     = 0.0045*(0.5 + u_ribbonWidth);
  float inten    = 0.0050;
  float deepI    = 0.0075;
  float deepS    = 7.0;
  if (m > 0.0) {
    // Squash the frame vertically, which draws the cells out into standing
    // columns; done before the rotation so the shafts stay aligned with the
    // surface overhead rather than with the pattern's orientation.
    // The frame is squashed hard in y and stretched slightly in x, so the cells
    // draw out into tall shafts without the whole field dropping in frequency —
    // dropping the frequency here was tried and it turns the net milky, which
    // is the one failure mode this pattern has.
    p = vec2(q.x, q.y*mix(1.0, 0.20, m))*rot(radians(u_rotation))*(zoom*mix(1.0, 1.30, m));
    swellAmp = mix(0.045, 0.13, m);
    // Only a slight softening: the filaments must stay filaments, or the dark
    // water between them fills in and there is nothing left to look at.
    sharp    = sharp*mix(1.0, 0.86, m);
    inten    = mix(0.0050, 0.0068, m);
    // Widening the dispersion is what keeps the drawn-out shafts chromatic
    // rather than three coincident white lines.
    disp     = disp*mix(1.0, 4.5, m);
    deepI    = mix(0.0075, 0.0092, m);
    deepS    = mix(7.0, 6.0, m);
  }

  // A long, slow swell so the whole net breathes instead of only shimmering;
  // at full morph it is the thing that bends the shafts.
  float swell = sin(p.x*2.1 - u_time*0.21) * cos(p.y*1.7 + u_time*0.17);
  p += vec2(swell, swell*0.6)*swellAmp;

  float t = u_time*0.40 + 12.0;
  float cr = caustic(p*(1.0+disp), t, inten, sharp);
  float cg = caustic(p,            t, inten, sharp);
  float cb = caustic(p*(1.0-disp), t, inten, sharp);

  vec3 net = vec3(cr, cg, cb);
  float lum = max(max(cr,cg),cb);

  // A second, much dimmer net further down: depth without a cost spike,
  // because it is the same field at a different scale and phase.
  float deep = caustic(p*0.55 + vec2(3.1,1.7), t*0.5, deepI, deepS);

  // Water body: near-black at the bottom of frame, opening up toward the light.
  float depth = smoothstep(-0.62, 0.55, q.y + 0.16*sin(q.x*1.6 + u_time*0.15));
  vec3 deepC = mix(u_shadow*0.35, u_colors[0].rgb*0.10, 0.5);
  vec3 nearC = mix(u_back*0.8, u_colors[1].rgb*0.20, 0.75);
  vec3 col = mix(deepC, nearC, depth);

  // Broad, very soft pool of scattered light so the dark half is not dead.
  float glow = 0.5 + 0.5*sin(p.x*1.1 + u_time*0.12)*cos(p.y*0.9 - u_time*0.10);
  col += mix(u_colors[1].rgb, u_colors[2].rgb, glow)*0.030*depth;

  col += palette(0.60)*deep*0.18;

  // Filaments. Core saturates to near-white, shoulder keeps the dispersed tint.
  vec3 fil = mix(palette(0.28), palette(0.50), clamp(lum*1.5, 0.0, 1.0));
  if (m > 0.0) {
    // A shaft covers more of the frame than a hairline did, so both additive
    // terms come down a little to hold the exposure and keep the water dark.
    // Same reasoning as above for the branch: at m=0 the original constants run.
    col += fil * net * mix(1.45, 1.20, m);
    col += vec3(1.0,0.98,0.94) * pow(clamp(lum,0.0,1.0), mix(2.6, 3.0, m)) * mix(0.85, 0.62, m);
  } else {
    col += fil * net * 1.45;
    col += vec3(1.0,0.98,0.94) * pow(clamp(lum,0.0,1.0), 2.6) * 0.85;
  }

  // Vignette keeps text legible in the corners.
  col *= 1.0 - dot(q,q)*0.50;

  col = clamp((col*(2.51*col+0.03))/(col*(2.43*col+0.59)+0.14), 0.0, 1.0);
  col = pow(col, vec3(1.0/2.2));
  float luma = dot(col, vec3(0.2126,0.7152,0.0722));
  col = clamp(mix(vec3(luma), col, u_saturation), 0.0, 1.0);
  float lvl = mix(255.0, 14.0, clamp(u_noise,0.0,1.0));
  col += (bayer4(gl_FragCoord.xy)-0.5)/lvl;
  col = floor(col*lvl+0.5)/lvl;
  fragColor = vec4(col, 1.0);
}
`;

// Light-slits fanned into spectra by a warped glass wedge
// Source: bench/variants/pat-opt-prism.js
const PRISM = /* glsl */ `#version 300 es
precision highp float;

uniform float u_time;
uniform vec2  u_resolution;
uniform vec4  u_colors[5];
uniform float u_ncols;
uniform vec3  u_back;
uniform vec3  u_shadow;
uniform float u_softness;
uniform float u_saturation;
uniform float u_noise;
uniform float u_rotation;
uniform float u_folds;
uniform float u_ribbon;
uniform float u_ribbonWidth;
// Universal 0..1 morph axis. 0 is the resting form (a linear grating fanned
// sideways); 1 curls the same grating into concentric rings and turns the
// dispersion radial, so the fans become a spectral diffraction halo.
uniform float u_morph;

out vec4 fragColor;

mat2 rot(float a){ float c=cos(a), s=sin(a); return mat2(c,-s,s,c); }

vec3 palette(float x){
  x=clamp(x,0.0,1.0)*(u_ncols-1.0);
  int i=int(floor(x)); float f=fract(x);
  return mix(u_colors[i].rgb, u_colors[min(i+1,int(u_ncols)-1)].rgb, smoothstep(0.0,1.0,f));
}

float bayer4(vec2 p){
  int m[16]=int[16](0,8,2,10, 12,4,14,6, 3,11,1,9, 15,7,13,5);
  return float(m[int(mod(p.y,4.0))*4 + int(mod(p.x,4.0))])/16.0;
}

// Rough spectral locus, x=0 violet .. x=1 red.
vec3 spectral(float x){
  x = clamp(x, 0.0, 1.0);
  return clamp(vec3(
    smoothstep(0.38, 0.66, x) - 0.5*smoothstep(0.92, 1.0, x) + 0.30*smoothstep(0.12, 0.0, x),
    smoothstep(0.20, 0.50, x)*smoothstep(1.0, 0.60, x)*1.4,
    smoothstep(0.46, 0.10, x)
  ), 0.0, 1.0);
}

// The grating: a family of thin, curved bright lines. They have to be THIN —
// a broad source just translates under dispersion instead of fanning out.
// The morph bends the grating's coordinate from a linear ramp in x to radial,
// so the straight slits close into rings. Interpolating the *argument* of the
// same sine keeps every intermediate a single coherent wavefront (curved
// slits) rather than a cross-fade of two gratings beating against each other.
// The two wobble terms are damped over the same range because a ring family
// modulated that hard just looks dented.
float slit(vec2 p, float m){
  // sqrt(r^2 + k) rather than length(): a true radius has a cone point at the
  // origin and it shows up as a hard black pinprick in the middle of the halo.
  // The offset rounds that tip off without changing anything further out.
  float ax = mix(p.x, sqrt(dot(p,p) + 0.30)*2.15, m);
  float w = ax*1.85
          + mix(1.35, 0.80, m)*sin(p.y*0.62 + u_time*0.09)
          + mix(0.55, 0.32, m)*sin(p.y*1.31 - u_time*0.13);
  float s = 0.5 + 0.5*sin(w + u_time*0.07);
  float line = pow(s, 34.0);
  // Every third line is brighter, which stops the grating looking mechanical.
  float env = 0.45 + 0.55*(0.5 + 0.5*sin(w*0.3333 - 0.7));
  return line*env;
}

// Glass wedge. Its gradient is the direction light gets bent in; two low
// frequencies keep the fans long and sweeping rather than chaotic.
float wedge(vec2 p){
  return sin(p.x*0.41 - p.y*0.33 + u_time*0.06)
       + 0.62*cos(p.x*0.27 + p.y*0.58 - u_time*0.05)
       + 0.30*sin(p.y*0.93 + u_time*0.08);
}

void main(){
  vec2 uv = gl_FragCoord.xy/u_resolution.xy;
  float asp = u_resolution.x/u_resolution.y;
  vec2 q = vec2((uv.x-0.5)*asp, uv.y-0.5);
  vec2 p = q*rot(radians(u_rotation))*(1.2 + 22.0/max(u_folds,1.0));

  float e = 0.06;
  float h = wedge(p);
  vec2  g = vec2(wedge(p+vec2(e,0.0)) - wedge(p-vec2(e,0.0)),
                 wedge(p+vec2(0.0,e)) - wedge(p-vec2(0.0,e)))/(2.0*e);
  float m = clamp(u_morph, 0.0, 1.0);
  // not normalised: steeper glass = wider fan. Morphing rotates the bend
  // direction toward the outward radial, which is what makes a ring disperse
  // into a halo instead of shearing sideways.
  // Same softened radius, so the bend direction fades out at the centre
  // instead of flipping across it.
  vec2 rd = p/sqrt(dot(p,p) + 0.30);
  vec2 bend = mix(g, rd*length(g)*1.25 + g*0.22, m);

  // How far apart the extreme wavelengths land, in the same units as p.
  float D = (2.1 + 1.6*u_ribbonWidth) * (0.55 + 0.45*u_softness) * mix(1.0, 1.30, m);

  vec3 col = vec3(0.0);
  const int N = 9;
  for(int i=0;i<N;i++){
    float x = float(i)/float(N-1);
    float bd = mix(1.0, -1.0, x)*0.5 + 0.5;   // 1 at violet, 0 at red
    float s = slit(p - bend*D*(0.25 + 0.75*bd), m);
    // Mostly the palette, lifted by a little true spectral colour. The fan is
    // meant to read as the brand ramp separating, not as a stock rainbow.
    vec3 tint = mix(palette(x), spectral(x), 0.38);
    col += tint * s;
  }
  col *= 2.5/float(N);

  // A dim, undispersed copy of the grating provides the white core of each
  // line, so the fans hang off something bright.
  float core = slit(p - bend*D*0.5, m);
  col += vec3(1.0,0.97,0.93)*pow(core, 2.0)*0.45;

  // Glass body: a faint sheen and a darkening where the wedge is steep.
  float steep = length(g);
  col += palette(0.5)*0.030*(0.4 + 0.6*(0.5+0.5*h));
  col *= 1.0 - 0.22*smoothstep(0.3, 1.8, steep);

  vec3 bg = mix(u_back, u_shadow, 0.5 + 0.5*h*0.6);
  col += bg;

  col *= 1.0 - dot(q,q)*0.40;

  col = clamp((col*(2.51*col+0.03))/(col*(2.43*col+0.59)+0.14), 0.0, 1.0);
  col = pow(col, vec3(1.0/2.2));
  float luma = dot(col, vec3(0.2126,0.7152,0.0722));
  col = clamp(mix(vec3(luma), col, u_saturation), 0.0, 1.0);
  float lvl = mix(255.0, 14.0, clamp(u_noise,0.0,1.0));
  col += (bayer4(gl_FragCoord.xy)-0.5)/lvl;
  col = floor(col*lvl+0.5)/lvl;
  fragColor = vec4(col, 1.0);
}
`;

// Iridescent film with thin order-contours, marbled by convection
// Source: bench/variants/pat-opt-soapfilm.js
const SOAPFILM = /* glsl */ `#version 300 es
precision highp float;

uniform float u_time;
uniform vec2  u_resolution;
uniform vec4  u_colors[5];
uniform float u_ncols;
uniform vec3  u_back;
uniform vec3  u_shadow;
uniform float u_softness;
uniform float u_saturation;
uniform float u_noise;
uniform float u_rotation;
uniform float u_folds;
uniform float u_ribbon;
uniform float u_ribbonWidth;
// Universal 0..1 morph axis. 0 is the resting form: a flat film draining top to
// bottom, so the interference orders lie in horizontal-ish bands. 1 re-points
// the drainage outward from the centre, i.e. the same film blown into a dome,
// and the orders become nested rings closing on a black rim.
uniform float u_morph;

out vec4 fragColor;

mat2 rot(float a){ float c=cos(a), s=sin(a); return mat2(c,-s,s,c); }

vec3 palette(float x){
  x=clamp(x,0.0,1.0)*(u_ncols-1.0);
  int i=int(floor(x)); float f=fract(x);
  return mix(u_colors[i].rgb, u_colors[min(i+1,int(u_ncols)-1)].rgb, smoothstep(0.0,1.0,f));
}

float bayer4(vec2 p){
  int m[16]=int[16](0,8,2,10, 12,4,14,6, 3,11,1,9, 15,7,13,5);
  return float(m[int(mod(p.y,4.0))*4 + int(mod(p.x,4.0))])/16.0;
}

vec3 spectral(float x){
  x = clamp(x, 0.0, 1.0);
  return clamp(vec3(
    smoothstep(0.38, 0.66, x) - 0.5*smoothstep(0.92, 1.0, x) + 0.30*smoothstep(0.12, 0.0, x),
    smoothstep(0.20, 0.50, x)*smoothstep(1.0, 0.60, x)*1.4,
    smoothstep(0.46, 0.10, x)
  ), 0.0, 1.0);
}

float hash21(vec2 p){
  vec3 p3=fract(vec3(p.xyx)*0.1031);
  p3+=dot(p3,p3.yzx+33.33);
  return fract((p3.x+p3.y)*p3.z);
}
float vnoise(vec2 p){
  vec2 i=floor(p), f=fract(p);
  f=f*f*(3.0-2.0*f);
  return mix(mix(hash21(i), hash21(i+vec2(1,0)), f.x),
             mix(hash21(i+vec2(0,1)), hash21(i+vec2(1,1)), f.x), f.y);
}
const mat2 m2 = mat2(0.80,-0.60,0.60,0.80);
// Two octaves. Thickness detail finer than one band spacing is exactly what
// turns interference colour grey, so the field is kept deliberately smooth.
float fbm(vec2 p){
  float f = 0.62*vnoise(p); p = m2*p*2.05;
  f += 0.31*vnoise(p);
  return f/0.93;
}

void main(){
  vec2 uv = gl_FragCoord.xy/u_resolution.xy;
  float asp = u_resolution.x/u_resolution.y;
  vec2 q = vec2((uv.x-0.5)*asp, uv.y-0.5);
  vec2 p = q*rot(radians(u_rotation)*0.25)*(1.7 + 21.0/max(u_folds,1.0));

  float t = u_time;

  // Convection: a domain warp that stirs the drainage gradient into marbling.
  // Two warp terms at different rates keep it from ever repeating visibly.
  vec2 w1 = vec2(fbm(p*0.42 + vec2(t*0.031, -t*0.019)),
                 fbm(p*0.42 + vec2(5.7 - t*0.024, 2.1 + t*0.017)));
  vec2 pw = p + (w1 - 0.5)*2.6;
  float swirl = fbm(pw*0.55 + vec2(-t*0.014, t*0.021));

  float m = clamp(u_morph, 0.0, 1.0);

  // Drainage: the film is thinnest at the top of frame and pools at the bottom.
  // The morph rotates that gradient from linear-in-y to radial-out-from-centre,
  // which is the same physics on a dome instead of a flat pane. Both fields are
  // monotonic, so their blend is monotonic too and the bands sweep round
  // continuously instead of re-sorting themselves.
  float drainFlat = 0.62 - 0.78*(uv.y - 0.5);
  float rr = length(vec2(q.x*0.86, q.y*1.30));
  float drainDome = 1.32 - 1.14*rr;
  float drain = mix(drainFlat, drainDome, m);
  // Swirl is eased back as the dome forms: the convective marbling is what
  // gives the flat film its character, but at ring scale it only smears the
  // orders together.
  float thick = clamp(drain + mix(1.05, 0.52, m)*(swirl - 0.45), 0.0, 2.4);

  // Slope -> viewing angle. Tilting shortens the path through the film, which
  // is what slides the bands as the surface moves.
  float e = 0.05;
  float hx = fbm((pw+vec2(e,0.0))*0.55) - fbm((pw-vec2(e,0.0))*0.55);
  float hy = fbm((pw+vec2(0.0,e))*0.55) - fbm((pw-vec2(0.0,e))*0.55);
  vec2 g = vec2(hx, hy)/(2.0*e);
  vec3 N = normalize(vec3(-g*0.30, 1.0));
  vec3 V = normalize(vec3(q*0.60, 1.0));
  float cosT = clamp(dot(N, V), 0.15, 1.0);

  // Optical path difference. Three-ish orders: enough for nested bands, few
  // enough that neighbouring orders never beat against each other.
  float opd = thick*(1.35 + 0.70*u_ribbonWidth)*cosT;

  // Colour by interference ORDER rather than by integrating wavelengths.
  // Averaging seven spectral samples is a desaturating operation, and with a
  // wide palette the averages land on muddy purples; mapping the order
  // directly onto the palette ramp keeps every band a clean palette colour
  // while still cycling with thickness exactly as a real film does.
  float order = opd*mix(0.85, 1.30, m);
  // Triangle wave, not fract: a sawtooth wraps 1->0 and leaves a hard seam
  // across the image at every order boundary.
  float hu = abs(fract(order)*2.0 - 1.0);
  // Restricted to a window of the ramp. Sweeping the full ramp puts its two
  // extremes side by side in every band pair, which reads as a heat map; a
  // narrow hue range is what makes iridescence look expensive.
  float hw = 0.14 + 0.50*hu;
  vec3 band = mix(palette(hw), spectral(hw), 0.20);

  // Antialias: where the bands are packed tighter than a pixel, fade to the
  // ramp's average instead of letting them alias into noise.
  float dens = fwidth(order);
  band = mix(palette(0.38)*0.9, band, smoothstep(0.55, 0.12, dens));

  // Visibility: contrast is highest at low order and washes out as the film
  // thickens, which is what gives a real film its pale, high-order centre.
  float vis = 0.45 + 0.55*exp(-order*0.30);
  vec3 film = band*vis;

  // The black film: below a quarter wavelength every colour cancels, so the
  // thinnest region goes genuinely black just before it would burst. This is
  // the detail that makes it read as a soap film rather than as a gradient.
  float black = smoothstep(0.0, 0.16, thick);
  film *= black;

  // Fresnel — the colour is a reflection, so it strengthens toward grazing.
  float fres = 0.45 + 0.75*pow(1.0 - cosT, 2.0);

  // A large-scale envelope: the film is only lit where the surrounding room
  // is reflected in it. Without this the frame is wall-to-wall colour and no
  // text will survive on top of it.
  // The floor lifts with the morph so the ring family reads as one continuous
  // dome rather than a few arcs picked out of the dark.
  float lit = mix(0.10, 0.40, m) + mix(0.90, 0.62, m)*smoothstep(0.20, 0.78, fbm(p*0.22 + vec2(t*0.012, 0.0)));

  vec3 col = mix(u_back*0.5, u_shadow*0.8, smoothstep(0.15, 0.85, swirl));
  col += film*fres*lit*0.70;

  // Specular: a broad soft source reflected in the film surface.
  vec3 L = normalize(vec3(-0.35, 0.62, 0.70));
  float spec = pow(clamp(dot(N, normalize(L+V)), 0.0, 1.0), 34.0/max(u_softness,0.3));
  col += mix(palette(0.55), vec3(1.0), 0.55)*spec*0.75*black*lit;

  col *= 1.0 - dot(q,q)*0.40;

  col = clamp((col*(2.51*col+0.03))/(col*(2.43*col+0.59)+0.14), 0.0, 1.0);
  col = pow(col, vec3(1.0/2.2));
  float luma = dot(col, vec3(0.2126,0.7152,0.0722));
  // Integrating seven wavelengths is inherently a desaturating operation, so
  // the film gets a little chroma back.
  col = clamp(mix(vec3(luma), col, u_saturation*0.95), 0.0, 1.0);
  float lvl = mix(255.0, 14.0, clamp(u_noise,0.0,1.0));
  col += (bayer4(gl_FragCoord.xy)-0.5)/lvl;
  col = floor(col*lvl+0.5)/lvl;
  fragColor = vec4(col, 1.0);
}
`;

// Chunky ordered dither; a drifting light posterised into woven shells
// Source: bench/variants/pat-gfx-dither.js
const DITHER = /* glsl */ `#version 300 es
precision highp float;

uniform float u_time;
uniform vec2  u_resolution;
uniform vec4  u_colors[5];
uniform float u_ncols;
uniform vec3  u_back;
uniform vec3  u_shadow;
uniform float u_softness;
uniform float u_saturation;
uniform float u_rotation;
uniform float u_folds;
uniform float u_ribbon;
uniform float u_ribbonWidth;
uniform float u_noise;
// 0 = drifting sunrise on an 8x8 Bayer checker (the resting form).
// 1 = the same shells folded back on themselves into topographic contour
//     rings, printed through a diagonal line screen instead of a checker.
uniform float u_morph;

out vec4 fragColor;

mat2 rot(float a){ float c=cos(a), s=sin(a); return mat2(c,-s,s,c); }

vec3 step_color(int i, int levels){
  // Lowest step is the background; the rest march through the palette.
  if(i<=0) return u_back*0.85 + u_shadow*0.35;
  float f = float(i-1)/max(1.0, float(levels-2));
  float x = clamp(f,0.0,1.0)*(u_ncols-1.0);
  int k = int(floor(x)); float fr = fract(x);
  return mix(u_colors[k].rgb, u_colors[min(k+1,int(u_ncols)-1)].rgb, fr);
}

// 8x8 Bayer via the classic recursive-fract trick — no 64-entry array.
float bayer2(vec2 a){ a = floor(a); return fract(a.x*0.5 + a.y*a.y*0.75); }
float bayer4(vec2 a){ return bayer2(0.5*a)*0.25 + bayer2(a); }
float bayer8(vec2 a){ return bayer4(0.5*a)*0.25 + bayer2(a); }

// A line-screen ordered-dither threshold: same job and same [0,1) distribution
// as bayer8, but its level sets are diagonal stripes instead of a checker, so
// the mid-tones cluster into engraved lines. Because it is just another
// threshold *field*, morphing between the two is a plain mix of two floats —
// each fat pixel crosses its own threshold at its own moment and the weave
// unravels into lines with no frame where the whole image re-quantises.
float lineDither(vec2 a){
  float u = (a.x + a.y)*0.1666667;
  return abs(fract(u) - 0.5)*2.0;
}

void main(){
  // Fat pixels. u_folds sets how fat.
  float px = max(2.0, floor(u_resolution.y/(13.0*max(u_folds,2.0))+0.5));
  vec2 fc = floor(gl_FragCoord.xy/px);
  vec2 res = u_resolution/px;
  vec2 uv = (fc+0.5)/res;
  float asp = res.x/res.y;
  vec2 p = vec2((uv.x-0.5)*asp, uv.y-0.5);
  // Orientation. Measured from the component default (52) so the shipped look
  // is bit-for-bit what it always was, while the knob still swings the whole
  // composition — this pattern simply had no orientation before.
  p = rot(radians(u_rotation - 52.0))*p;

  float t = u_time*0.16;

  // A single light source low in frame, falling off in wide concentric shells.
  // Everything else only bends those shells — so the dithered transitions
  // always read as nested arcs, i.e. as a deliberate figure.
  vec2 sunp = vec2(0.20*sin(t*0.45), -0.30 + 0.05*sin(t*0.71));
  float rr = length((p - sunp)*vec2(0.80, 1.15));
  // A slow swell bends the shells without breaking them up.
  rr += 0.060*sin(p.x*3.1 - t*1.3) + 0.035*sin(p.x*6.3 + p.y*2.2 + t*0.9);
  // MORPH, part 1: fold the distance field back on itself. The amplitude ramps
  // from zero, so the shells first ripple, then (once the fold exceeds the band
  // spacing) each shell reflects into a pair of contour rings. The band *count*
  // is untouched — it is the field that folds, which is why nothing snaps.
  rr += u_morph*0.10*sin(rr*11.0 - t*1.6);
  // Wide enough that the outermost shell still reaches the top corners: no
  // dead flat black third at the top of the frame.
  float v = 1.0 - smoothstep(0.04, 1.35, rr);
  v = clamp(v*1.10 - 0.02, 0.0, 1.0);

  int levels = int(clamp(u_ncols+1.0, 3.0, 6.0));
  float L = float(levels-1);
  // MORPH, part 2: cross-fade the threshold field, checker -> line screen.
  float d = mix(bayer8(fc), lineDither(fc), u_morph) - 0.5;
  float q = v*L + d*(0.9+0.5*u_softness)*mix(1.0, 1.45, u_morph);
  int lo = int(clamp(floor(q), 0.0, L));
  vec3 col = step_color(lo, levels);

  float l = dot(col, vec3(0.2126,0.7152,0.0722));
  col = mix(vec3(l), col, u_saturation);
  fragColor = vec4(pow(clamp(col,0.0,1.0), vec3(1.0/2.2)), 1.0);
}
`;

// Screen-printed halftone, three inks on classic separation angles
// Source: bench/variants/pat-gfx-halftone.js
const HALFTONE = /* glsl */ `#version 300 es
precision highp float;

uniform float u_time;
uniform vec2  u_resolution;
uniform vec4  u_colors[5];
uniform float u_ncols;
uniform vec3  u_back;
uniform vec3  u_shadow;
uniform float u_softness;
uniform float u_saturation;
uniform float u_rotation;
uniform float u_folds;
uniform float u_ribbon;
uniform float u_ribbonWidth;
uniform float u_noise;
// 0 = round-dot screen, tight registration (the resting form).
// 1 = the same separations pulled through a coarser LINE screen with the
//     plates deliberately thrown further out of register.
uniform float u_morph;

out vec4 fragColor;

mat2 rot(float a){ float c=cos(a), s=sin(a); return mat2(c,-s,s,c); }

// Three plates pulled from across the whole ramp, not off its front — with a
// 5-stop palette that picks stops 0/2/4, so the inks are actually different
// colours instead of three neighbours that print as one.
vec3 ink(int i, int N){
  int n = int(max(u_ncols, 1.0));
  int k = N<=1 ? 0 : int(floor(float(i)*float(n-1)/float(N-1) + 0.5));
  return u_colors[clamp(k, 0, n-1)].rgb;
}

float hash12(vec2 p){
  vec3 p3 = fract(vec3(p.xyx)*0.1031);
  p3 += dot(p3, p3.yzx+33.33);
  return fract((p3.x+p3.y)*p3.z);
}

// Blob field. k shifts the whole composition per ink so the separations do not
// sit on top of each other — that is where the colour mixing comes from.
float field(vec2 q, float k){
  float t = u_time*0.11;
  float s = 0.0;
  for(int i=0;i<3;i++){
    float fi = float(i);
    float ph = fi*2.399 + k*0.9;
    vec2 c = vec2(cos(t*1.10+ph)*0.62, sin(t*0.83+ph*1.7)*0.30);
    float r = 0.30 + 0.07*sin(t*1.7+ph);
    s += r*r/(dot(q-c,q-c)+0.020);
  }
  s *= 0.62;
  s += 0.34 + 0.34*sin(dot(q, vec2(1.35,0.95)) - t*1.6 + k*1.3);
  return s;
}

void main(){
  vec2 uv = gl_FragCoord.xy/u_resolution.xy;
  float asp = u_resolution.x/u_resolution.y;
  vec2 p = vec2((uv.x-0.5)*asp, uv.y-0.5);

  // Paper: the background colour with a whisper of tooth.
  float tooth = hash12(floor(gl_FragCoord.xy*0.5));
  vec3 col = u_back*(0.94+0.12*tooth) + u_shadow*0.10;

  // u_folds is the screen ruling: bigger zoom = finer dot pitch. The morph
  // coarsens it continuously (the grid scales, it never re-tiles).
  float pitch = max(u_folds, 2.0)*2.3*mix(1.0, 0.68, u_morph);
  int N = int(clamp(u_ncols, 1.0, 3.0));

  for(int i=0;i<3;i++){
    if(i>=N) break;
    float fi = float(i);
    // Registration error: each plate drifts on its own slow ellipse.
    vec2 mis = vec2(cos(u_time*0.19+fi*2.1), sin(u_time*0.23+fi*1.3))*0.024*(0.4+fi*0.6)
               *mix(1.0, 2.4, u_morph);
    float a = field(p+mis, fi*1.7);
    a = smoothstep(0.78, 1.85, a);
    // Each ink keeps to its own region of the sheet, so the plates overlap in
    // narrow seams rather than everywhere: that is where the paper shows.
    a *= 1.0 - mix(0.85, 0.62, u_morph)*smoothstep(0.42, 1.15, length((p-vec2(0.0,0.0))*vec2(0.80,1.25)));
    a = clamp(a, 0.0, 1.0);

    // Classic separation angles, carried around by u_rotation.
    vec2 sp = rot(radians(u_rotation + 15.0 + fi*30.0))*(p+mis*0.5)*pitch;
    vec2 cell = fract(sp)-0.5;
    // MORPH: blend the DOT distance field into a LINE distance field. Both are
    // distances in the same cell, so the level set (which is what you actually
    // see) sweeps continuously: circle -> stadium -> ellipse stretched until
    // neighbouring cells touch and fuse into a continuous rule. Nothing about
    // the grid, the ink count or the tone mapping changes.
    float d = mix(length(cell), abs(cell.y), u_morph);
    // Capped below 0.5 so neighbouring dots never merge into a solid: the
    // screen stays legible as a screen even at full ink.
    float r = 0.455*sqrt(a);
    float aa = max(fwidth(d), 0.0015)*0.9;
    float cov = 1.0 - smoothstep(r-aa, r+aa, d);
    col = mix(col, ink(i, N)*1.02, cov*0.92);
  }

  float l = dot(col, vec3(0.2126,0.7152,0.0722));
  col = mix(vec3(l), col, u_saturation);
  fragColor = vec4(pow(clamp(col,0.0,1.0), vec3(1.0/2.2)), 1.0);
}
`;

// Soft gradient mesh — one drifting control point per palette colour
// Source: bench/variants/pat-gfx-mesh.js
const MESH = /* glsl */ `#version 300 es
precision highp float;

uniform float u_time;
uniform vec2  u_resolution;
uniform vec4  u_colors[5];
uniform float u_ncols;
uniform vec3  u_back;
uniform vec3  u_shadow;
uniform float u_softness;
uniform float u_saturation;
uniform float u_rotation;
uniform float u_folds;
uniform float u_ribbon;
uniform float u_ribbonWidth;
uniform float u_noise;
// 0 = the soft gradient mesh (the resting form).
// 1 = the same control points as a cut-paper colour field: hard-edged cells
//     with topographic contour terraces stepping down from each centre.
uniform float u_morph;

out vec4 fragColor;

mat2 rot(float a){ float c=cos(a), s=sin(a); return mat2(c,-s,s,c); }

float bayer4(vec2 p){
  int m[16] = int[16](0,8,2,10, 12,4,14,6, 3,11,1,9, 15,7,13,5);
  return float(m[int(mod(p.y,4.0))*4 + int(mod(p.x,4.0))])/16.0;
}

void main(){
  vec2 uv = gl_FragCoord.xy/u_resolution.xy;
  float asp = u_resolution.x/u_resolution.y;
  vec2 p = vec2((uv.x-0.5)*asp, uv.y-0.5);
  p = rot(radians(u_rotation)*0.25)*p;

  float t = u_time*0.13;
  float sc = 9.0/max(u_folds,3.0);
  // Zoom applied to the mesh itself, damped: this look is full-bleed by design,
  // so the control points may spread and tighten but must not shrink off the
  // frame at high zoom values. Written as 1 + (sc-1)*k, not mix(), so it is
  // exactly 1.0 at the component default (u_folds 9) with no rounding.
  float msc = 1.0 + (sc - 1.0)*0.6;

  // Two cheap sine layers as a domain warp: enough to make the blob edges
  // organic without any noise fetches.
  vec2 w = vec2(
    sin(p.y*2.7*sc + t*1.7) + 0.5*sin(p.x*4.1*sc - t*1.1),
    cos(p.x*2.3*sc - t*1.3) + 0.5*cos(p.y*3.7*sc + t*1.9)
  );
  vec2 q = p + w*0.085/sc;

  int N = int(clamp(u_ncols,1.0,5.0));
  vec3 acc = vec3(0.0);
  float wsum = 0.0;
  float peak = 0.0;
  for(int i=0;i<5;i++){
    if(i>=N) break;
    float fi = float(i);
    float ph = fi*2.399;
    // msc is the zoom: it scales the control-point orbits and their radii
    // together, so u_folds dollies the whole mesh in and out instead of only
    // retuning the edge warp.
    vec2 c = vec2(
      0.62*asp*0.62*sin(t*(0.71+0.13*fi) + ph),
      0.34*cos(t*(0.53+0.17*fi) + ph*1.7)
    )*msc;
    float r = (0.58 + 0.10*sin(t*0.9+ph))*max(u_softness,0.3)*msc;
    float d = length((q-c)*vec2(0.80,1.05))/r;
    // Wide skirt, very sharp weighting: the nearest control point owns its
    // region outright (no five-way average, which is what turns a mesh muddy)
    // while the tails still overlap enough to hand over without a crease.
    float g = exp(-d*d*0.85);
    float g3 = g*g*g;
    float gw = g3*g3;
    // MORPH, part 1: raise the blend exponent. The weighting is already a
    // soft-max; pushing the exponent up narrows the hand-over zone between
    // control points until the mesh reads as cut paper. It is one continuous
    // parameter — the cell boundaries tighten, they never appear.
    // (pow() is skipped entirely at rest so morph=0 is bit-exact.)
    if(u_morph > 0.0) gw = pow(gw, 1.0 + 2.6*u_morph);
    gw += 1e-4;
    acc += u_colors[i].rgb*gw;
    wsum += gw;
    peak = max(peak, g);
  }
  vec3 mesh = acc/max(wsum, 1e-4);

  // Full-bleed: the mesh covers the frame, the background only tints the very
  // weakest corners. Wide flats of colour are the point of this look.
  float cover = smoothstep(0.03, 0.36, peak);
  vec3 bg = mix(u_back, u_shadow, 0.5);
  vec3 col = mix(bg, mesh, cover);

  // MORPH, part 2: topographic terraces. peak is a continuous height field,
  // so the contour count is FIXED and only the step edge sharpens: at low morph
  // the "steps" are a smooth ramp of zero amplitude, and they harden into
  // printed contour bands. No band is ever added or removed.
  if(u_morph > 0.0){
    float ph = pow(clamp(peak,0.0,1.0), 0.65)*6.0;
    float e = max(fwidth(ph)*0.9, mix(0.50, 0.05, u_morph));
    float terr = smoothstep(0.5-e, 0.5+e, fract(ph));
    col *= mix(1.0, 0.78+0.42*terr, u_morph);
  }

  // A broad sheen so the field has a light direction.
  col *= 0.90 + 0.22*smoothstep(-0.55,0.55, p.y*0.6 + p.x*0.4);

  // Corner falloff keeps text legible at the edges.
  col *= 1.0 - 0.34*dot(p*vec2(0.56,1.00), p*vec2(0.56,1.00));

  float l = dot(col, vec3(0.2126,0.7152,0.0722));
  col = mix(vec3(l), col, u_saturation);
  col = pow(clamp(col,0.0,1.0), vec3(1.0/2.2));
  col += (bayer4(gl_FragCoord.xy)-0.5)/160.0;
  fragColor = vec4(clamp(col,0.0,1.0), 1.0);
}
`;

// Fragment shader per pattern. `fold` is absent on purpose — the component
// imports it directly so that tree of code stays with its LUT.
export const PATTERN_SHADERS: Record<Exclude<PatternName, 'fold'>, string> = {
	aurora: AURORA,
	curl: CURL,
	ink: INK,
	oilfilm: OILFILM,
	marble: MARBLE,
	caustics: CAUSTICS,
	prism: PRISM,
	soapfilm: SOAPFILM,
	dither: DITHER,
	halftone: HALFTONE,
	mesh: MESH
};
